---
title: "The Impact of Light Rails on Air Pollution"
author: Thanicha Ruangmas, Geoffrey Zhang
bibliography: references.bib
csl: apa.csl
---

## Introduction

Air pollution is harming human health. According to the [@world_health_organization_ambient_nodate], around the world, 99 percent of the human population is exposed to harmful levels of air pollution. In America, a major contributing factor to air pollution is heavy traffic congestion near urban centers, a problem made worse by the car-centric environment of the United States [@pucher_united_1996]. To combat traffic congestion, urban cities around the country are turning to various public transit solutions to take cars off the road and reduce air pollution. One such solution is light rail, a form of public transit that combines features from buses and subways. Compared to buses, light rails are higher capacity and operate more frequently in urban areas. Furthermore, since light rails run on electricity, they are more environmentally friendly than bus routes. Light rails also have the advantage over subways of running above ground, requiring less construction to build a new system. As such, light rails often stop at more locations and can reach more residents [@texas_am_transportation_institute_light-rail_nodate].

Our study aims to quantify the air pollution impact of opening a light rail system in an urban center. We hypothesize that opening such a system will reduce air pollution in a city by taking cars off the road, a finding that similar studies on other modes of public transportation have found. Past studies have focused on subway systems or have focused on non-US countries, and have typically simulated the impact of an opening. Our ex-post study aims to introduce new findings that simulations cannot capture, presenting critical evidence to help policymakers build more public transportation in urban centers.

<!--# TR will describe Identification Strategy -->

## Literature Review

<!--# Add Literature Review here -->

## Data

### Light Rail Routes

<!--# GZ explain why the four cities were chosen -->

To create a panel of cities for this study, we considered multiple criteria. Generally speaking, light rail systems in the United States can be divided into two categories: first-generation legacy systems that evolved from older streetcars and trolleys, and second-generation modern systems designed from the ground up for rolling stock that can travel longer distances and carry more passengers. Because the dataset we use for air pollution only has data from 2000 to 2018, only light rail systems opened after 2002 were considered in our study, limiting our panel of cities to second-generation systems. To account for potential air pollution reductions caused by other modes of transportation, our panel of cities was also sorted into cities that had multiple modes of public rail transit, and cities that exclusively had light rail in their public transit system. This allows us to more definitively conclude whether the opening of a light rail system itself is reducing air pollution, instead of increased public transit ridership from more connected systems. Finally, a minimum light rail system length of 15 miles was set to ensure the systems we analyzed covered the majority of an urban center. After considering these criteria, our panel of cities was narrowed down to four systems: Charlotte, North Carolina's LYNX system, Houston, Texas's METRORail system, Minneapolis-St. Paul, Minnesota's METRO system, and Phoenix, Arizona's Valley Metro Rail system.

### PM2.5

<!--# GZ will need to clarify this section. -->

To calculate PM2.5 in an urban center, we use a dataset from Washington University in St. Louis's Atmospheric Composition Analysis Group that estimates ground-level PM2.5 from 2000 to 2018. The North American Regional Estimates (V4.NA.03) dataset estimates monthly ground-level PM2.5 by combining Aerosol Optical Depth (AOD) data from NASA's MODIS, MISR, and SeaWIFS instruments, providing us with air pollution data across the United States at a gridded resolution of 0.01°. We use this data to calculate the monthly mean PM2.5 before and after the opening of a light rail system for a 10km buffer around each of our control cities' city centers. City center coordinates were found by using the Google Maps Geocoding API.
